source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '6.0'

target :ExampleSSDataSources do
  pod 'SSDataSources', :path => "../SSDataSources.podspec"
end

target :ExampleSSDataSourcesTests do
  pod 'Expecta'
  pod 'OCMock'
  pod 'MagicalRecord'
end
